### ISSUE TITLE
Fix anything other than food having a quality

### ISSUE THREAD

**Issue by Cyberillc** [s5y-ux/ExpandedCooking#1]
I was smelting some iron and it gave it a food quality. It also prevents multiple iron ingots from being in the furnace at the same time.

https://github.com/s5y-ux/ExpandedCooking/assets/142674955/ff373f85-942b-4499-a90e-ad85b9865c37

**Comment by s5y-ux** [comment]
Thank you very much for bringing this up to my attention.

I will fix this in a couple minutes

**Comment by s5y-ux** [comment]
The problem was on line 56 in the "CookedFood" class. When I was calling the event, I overlooked a logical check to make sure that the resulting item existed in the array of foods that were available for an EXP boost. To do this, I implemented a binary search method and updated the logic check to make sure the Material of the result existed in the array of foods.
Another way I could have fixed this was converting the array into a set and using the contains() method.

-Ill be updating a release and marking this issue closed. Please let me know if you run into any more bugs.

Thank you for using Expanded Cooking :)

```Java
private boolean binarySearch(Material[] materialList, Material item) {
		for(Material mat: materialList) {
			if(mat.equals(item)) {
				return(true);
			}
		}
		return(false);
	}

	@EventHandler
    public void onFurnaceSmelt(FurnaceSmeltEvent event) {
    	try {
    	
    		if(binarySearch(this.EXPData.Foods, event.getResult().getType())) {
   
    	Block furnaceBlock = event.getBlock();
        Location furnaceLocation = furnaceBlock.getLocation();
    	Player player = furnaceInteractions.get(furnaceLocation);
        ItemStack resultItem = event.getResult();
        ItemMeta resultItemMeta = resultItem.getItemMeta();
        List<String> Lore = new ArrayList<String>();
        PlayerData ourPlayer = new PlayerData(main, player);
        Lore.add(ourPlayer.getCookQuality());
        Lore.add(ourPlayer.getChef());
        resultItemMeta.setLore(Lore);
        resultItem.setItemMeta(resultItemMeta);
    		}
    		}
    	catch (Exception e) {
    		event.setCancelled(true);
    	}
    
    }
```

**Comment by s5y-ux** [comment]
https://github.com/s5y-ux/ExpandedCooking/releases/tag/1.3.2
